services:
  - type: worker
    name: telegram-number-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
      envVars:
      - key: BOT_TOKEN
        value: 8884774315:AAH-AJ7R8gSM2rlsXCVKVoY4c7rhwqdxm0
        sync: false
      - key: ADMIN_ID
        value: 8242348109
        sync: false
